var BookIt = BookIt || {};
BookIt.Settings = BookIt.Settings || {};
BookIt.Settings.signUpUrl = "/e/rest/account/register"; //"http://127.0.0.1:30000/api/account/register";
BookIt.Settings.signInUrl = "/e/rest/login/login";
BookIt.Settings.deleteSessionUrl = "/e/rest/login/session";
BookIt.Settings.measurePowerURL= "/e/rest/power/measure";
BookIt.Settings.getLastPowerMeasureURL= "/e/rest/power/measure/last";
BookIt.Settings.getAllPowerMeasureURL= "/e/rest/power/measure";
BookIt.Settings.getAllPowerSuppliesURL= "/e/rest/power/supplies";
